### ISSUE TITLE
Issue related to Stage 2

### ISSUE THREAD

**Issue by surenyi** [TencentAILabHealthcare/scpDeconv#6]
**This is a great work!
When I test the software, there is an error accured related to GPU and CPU conversion. Please help me to solve this issue!!! Thanks a lot!
Below is the logs of issue.**

(base) [root@e5c3b37c390c /scpDeconv]# python3 main.py --dataset murine_cellline
------Start Running scpDeconv------
------Start Running Stage 1 : Mixup reference------
The dim of source data is :
(4000, 919)
The dim of target data is :
(1000, 919)
Stage 1 : Mixup finished!
------Start Running Stage 2 : Training AEimpute model------
============= Epoch 10/200 in stage2 =============
cAE_loss=0.121458, pred_loss=0.001081, recon_loss=0.120378
============= Epoch 20/200 in stage2 =============
cAE_loss=0.093459, pred_loss=0.000963, recon_loss=0.092497
============= Epoch 30/200 in stage2 =============
cAE_loss=0.072402, pred_loss=0.000963, recon_loss=0.071439
============= Epoch 40/200 in stage2 =============
cAE_loss=0.056012, pred_loss=0.000985, recon_loss=0.055027
============= Epoch 50/200 in stage2 =============
cAE_loss=0.045071, pred_loss=0.000921, recon_loss=0.044150
============= Epoch 60/200 in stage2 =============
cAE_loss=0.035229, pred_loss=0.000909, recon_loss=0.034320
============= Epoch 70/200 in stage2 =============
cAE_loss=0.028749, pred_loss=0.000941, recon_loss=0.027808
============= Epoch 80/200 in stage2 =============
cAE_loss=0.022595, pred_loss=0.000783, recon_loss=0.021812
============= Epoch 90/200 in stage2 =============
cAE_loss=0.017937, pred_loss=0.000807, recon_loss=0.017130
============= Epoch 100/200 in stage2 =============
cAE_loss=0.013607, pred_loss=0.000844, recon_loss=0.012763
============= Epoch 110/200 in stage2 =============
cAE_loss=0.009698, pred_loss=0.000727, recon_loss=0.008971
============= Epoch 120/200 in stage2 =============
cAE_loss=0.005444, pred_loss=0.000753, recon_loss=0.004691
============= Epoch 130/200 in stage2 =============
cAE_loss=0.002402, pred_loss=0.000656, recon_loss=0.001746
============= Epoch 140/200 in stage2 =============
cAE_loss=0.001903, pred_loss=0.000602, recon_loss=0.001301
============= Epoch 150/200 in stage2 =============
cAE_loss=0.001741, pred_loss=0.000547, recon_loss=0.001194
============= Epoch 160/200 in stage2 =============
cAE_loss=0.001664, pred_loss=0.000548, recon_loss=0.001115
============= Epoch 170/200 in stage2 =============
cAE_loss=0.001553, pred_loss=0.000498, recon_loss=0.001055
============= Epoch 180/200 in stage2 =============
cAE_loss=0.001448, pred_loss=0.000464, recon_loss=0.000984
============= Epoch 190/200 in stage2 =============
cAE_loss=0.001308, pred_loss=0.000422, recon_loss=0.000885
============= Epoch 200/200 in stage2 =============
cAE_loss=0.001307, pred_loss=0.000425, recon_loss=0.000882
Traceback (most recent call last):
  File "/scpDeconv/main.py", line 57, in <module>
    main()
  File "/scpDeconv/main.py", line 35, in main
    source_recon_data = model_im.train(source_data, target_data)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scpDeconv/model/AEimpute_model.py", line 153, in train
    SaveLossPlot(self.outdir, metric_logger, loss_type = ['cAE_loss','pred_loss','recon_loss'], output_prex = 'Loss_plot_stage2')
  File "/scpDeconv/model/utils.py", line 55, in SaveLossPlot
    plt.plot(metric_logger[loss_type[i]])
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/pyplot.py", line 3794, in plot
    return gca().plot(
           ^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/axes/_axes.py", line 1779, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 296, in __call__
    yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 478, in _plot_args
    x, y = index_of(xy[-1])
           ^^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/cbook.py", line 1719, in index_of
    y = _check_1d(y)
        ^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/matplotlib/cbook.py", line 1411, in _check_1d
    return np.atleast_1d(x)
           ^^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/numpy/core/shape_base.py", line 65, in atleast_1d
    ary = asanyarray(ary)
          ^^^^^^^^^^^^^^^
  File "/miniconda3/lib/python3.12/site-packages/torch/_tensor.py", line 1083, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**You may contact me at [10416@zju.edu.cn].
Looking forward to your reply!**

**Comment by surenyi** [comment]
I have
